### ISSUE TITLE
怎么才能在unity工程中调式这个ugui的代码呢？

### ISSUE THREAD

**Issue by wangjianpeng** [jareguo/unity-ugui#1]
比如有想在Eventsyste中打断点，但是总是进不去。就算是我用修改过的ugui已经替换掉了原来的ugui的dll，只能打log，但是就是无法进到eventsystem 的断点里。后来看到unity 又从一个c盘下的build的路径下，加载了代码，怀疑跟这个有关系。请教怎么办呢？

**Comment by jareguo** [comment]
抱歉不太清楚，可能跟调试工具的使用方法有关
